# Generated by Django 4.0.6 on 2022-09-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_fav',
            field=models.BooleanField(default=False, verbose_name='is favorite'),
        ),
    ]
