# Generated by Django 4.0.6 on 2022-09-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_banner_alter_product_is_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(max_length=6, verbose_name='رمز اللون (HEX)'),
        ),
    ]
