# Generated by Django 4.0.6 on 2022-09-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ImageField(height_field=330, upload_to='banners/', width_field=450),
        ),
    ]
