# Generated by Django 4.0.6 on 2022-09-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_color_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(help_text='ادخل اللون مثل: OxFF45B9EE', related_name='products', to='store.color', verbose_name='الالوان'),
        ),
    ]
