# Generated by Django 4.0.6 on 2022-09-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(help_text='ادخل اللون مثل: OxFF45B9EE', max_length=6, verbose_name='رمز اللون (HEX)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='store.color', verbose_name='الالوان'),
        ),
    ]
