# Generated by Django 4.0.6 on 2022-09-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ImageField(upload_to='banners/'),
        ),
    ]
