# Generated by Django 4.0.6 on 2022-09-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_color_color_code_alter_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(help_text='ادخل اللون مثل: OxFF45B9EE', max_length=12, verbose_name='رمز اللون (HEX)'),
        ),
    ]
